### ISSUE TITLE
Travis configuration

### ISSUE THREAD

**Issue by gaborbencebekesi** [BME-MIT-IET/Szemantikusok-iet-2018#1]
We will use Travis for continuous integration.

**Comment by gaborbencebekesi** [comment]
Travis support added by @gaborbencebekesi with commit 8a8fc75168993999669f6f02067fdbb2af0e148c.
Travis configured for Gradle by @andrewer04 with commit 5f6ca72f21168130fbd6db07021218ac54b07e66.
Travis permission granted by @gaborbencebekesi with commit 9a4dba57a304ca6fa5aee8b7d52d4b477a68aeb8.

**Comment by adamkassai** [comment]
Travis is perfectly configured.
