### ISSUE TITLE
Wiki pages

### ISSUE THREAD

**Issue by adamkassai** [BME-MIT-IET/Szemantikusok-iet-2018#13]
Wiki is activated for our GitHub repository.

**Comment by adamkassai** [comment]
Created Wiki page for SonarQube static code analysis.

**Comment by gaborbencebekesi** [comment]
Created Wiki page for Codacy static code analysis.

**Comment by gaborbencebekesi** [comment]
Created Wiki page for Travis CI configuration.

**Comment by andrewer04** [comment]
Created Wiki page for Docker configuration.

**Comment by gulyasadam15** [comment]
Created Wiki page for manual code-review.

**Comment by adamkassai** [comment]
Created Wiki page for Cucumber feature testing.
