### ISSUE TITLE
Create and/or modify JUnit tests.

### ISSUE THREAD

**Issue by gaborbencebekesi** [BME-MIT-IET/Szemantikusok-iet-2018#15]
Create some JUnit test for basic functions.

**Comment by gaborbencebekesi** [comment]
After the workspace configured, I ran the tests already written.
![image](https://user-images.githubusercontent.com/20973318/39882219-774cd270-5483-11e8-9a8d-7f7875501ba9.png)
Summary: 69% classes, 77% lines covered by the tests,

**Comment by gaborbencebekesi** [comment]
According to the code coverage, short primitive was not tested in beans. Successfully added and tested.

**Comment by gaborbencebekesi** [comment]
According to the code coverage, there was not class without default constructor.

**Comment by gaborbencebekesi** [comment]
Simple null parameter passing tests added.

**Comment by gaborbencebekesi** [comment]
![image](https://user-images.githubusercontent.com/20973318/39945557-3f834200-556b-11e8-9b5e-558887b47f84.png)
Now 75% classes, 79% lines covered.

**Comment by gaborbencebekesi** [comment]
Pull request created: https://github.com/BME-MIT-IET/Szemantikusok-iet-2018/pull/18.

**Comment by gulyasadam15** [comment]
Very nice job! I will continue to add same test cases.

**Comment by andrewer04** [comment]
https://github.com/BME-MIT-IET/Szemantikusok-iet-2018/issues/19
