### ISSUE TITLE
Subject test error

### ISSUE THREAD

**Issue by andrewer04** [BME-MIT-IET/Szemantikusok-iet-2018#19]
The serialization of  a Subject class is not correct. The inicialization creates IET classes for Subject's results list, which is a subclass of Result. The problem is, after serilaization, the RDFMapper reads back the Subject class with it's results list, but the type of results is Result, not IET, and therefore only the neptun property will be read. This is why the assertaion not works.

**Comment by gaborbencebekesi** [comment]
Problem solved (with workaround) in commit 33f12de0e70e8450a56655e249398422615a632f.
