### ISSUE TITLE
Creating BDD tests

### ISSUE THREAD

**Issue by andrewer04** [BME-MIT-IET/Szemantikusok-iet-2018#4]
Create BDD test with Cucumber or Specflow.

**Comment by adamkassai** [comment]
I had to make some more configuration in commit https://github.com/BME-MIT-IET/Szemantikusok-iet-2018/commit/a620f1b407a7f591e7d40d1262cc85ed328caca2.
Then I could create my first Cucumber feature test in commit https://github.com/BME-MIT-IET/Szemantikusok-iet-2018/commit/50e6dcbf568dab193ca084757d817be26f9eeae9.

**Comment by adamkassai** [comment]
You can see all these changes in pull request #21.

**Comment by adamkassai** [comment]
@andrewer04 approved these changes.
