### ISSUE TITLE
Code coverage

### ISSUE THREAD

**Issue by andrewer04** [BME-MIT-IET/Szemantikusok-iet-2018#5]
Measure code coverage and expand tests.

**Comment by gaborbencebekesi** [comment]
After the workspace configured, I ran the tests already written.
There are 47 test cases. All passed.
![image](https://user-images.githubusercontent.com/20973318/39882219-774cd270-5483-11e8-9a8d-7f7875501ba9.png)
Summary: 69% classes, 77% lines covered by the tests,

**Comment by gaborbencebekesi** [comment]
According to the code coverage, short primitive was not tested in beans. Successfully added and tested in unit tests.

**Comment by gaborbencebekesi** [comment]
According to the code coverage, there was not class without default constructor.

**Comment by gaborbencebekesi** [comment]
Simple null parameter passing tests added.

**Comment by gaborbencebekesi** [comment]
![image](https://user-images.githubusercontent.com/20973318/39945590-65beca0c-556b-11e8-868e-213fab238e4c.png)
Now 75% classes, 79% lines covered.
